### ISSUE TITLE
Release not working correctly on Windows

### ISSUE THREAD

**Issue by marcinbiegun** [keijiro/Ngx#2]
Hi Keijiro, thanks for releasing awesome this project! I'm really interested into running it and learning my own models.

I've started with downloading a release and running it on a Windows 10 machine with GTX1080. I think there is something wrong with the image I get, it looks like the pix2pix models do not return a correct image. This is what I see:

![bad_ngx](https://user-images.githubusercontent.com/472392/47207138-c5116800-d38a-11e8-923b-3b573eaa1050.jpg)

Any ideas?

**Comment by keijiro** [comment]
Actually I'm not sure what's happening on your side, but I think it's related to an issue happened on [Pix2Pix](https://github.com/keijiro/Pix2Pix) that was easily resolved by updating the graphics driver.

So, could you try updating the driver to the latest version?

**Comment by marcinbiegun** [comment]
You are right, that was the drivers issue. I've updated Nvidia drivers to latest 416.34 and now it works perfectly fine. Thanks!
