### ISSUE TITLE
Issue with pix2pix export collab notebook

### ISSUE THREAD

**Issue by ethanstickley** [keijiro/Ngx#6]
I've had success with the 3 training collab notebooks in the past however now when revisiting the project there are errors. I was able to get the first two notebooks working with some modifications however I'm stuck on the final 'pix2pix export' notebook used to generate the .pict file.

Below is the error message I'm receiving. Any help would be appreciated!
-------------------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

[<ipython-input-27-fe0d2b17e583>](https://localhost:8080/#) in <module>()
     17 with tempfile.TemporaryDirectory() as tmp_dir:
     18   from tensorflow_checkpoint_dumper import TensorflowCheckpointDumper
---> 19   dumper = TensorflowCheckpointDumper(checkpoint_file, tmp_dir, '')
     20   dumper.build_and_dump_vars()
     21 

[/content/tensorflow_checkpoint_dumper.py](https://localhost:8080/#) in __init__(self, checkpoint_file, output_dir, remove_variables_regex)
     60   <meta name="github-keyboard-shortcuts" content="source-code" data-pjax-transient="true" />
     61 
---> 62 
     63   <meta name="selected-link" value="/ethanstickley/TF/blob/ca4c632f94033c9ec0903a1de6f8d0428bc818db/TensorFlowCheckpointDumper.py" data-pjax-transient>
     64 

AttributeError: module 'tensorflow._api.v2.train' has no attribute 'NewCheckpointReader'

**Comment by keijiro** [comment]
Sorry but I can't remember anything I did in this repository four years ago. Sadly, I have no idea how to fix it.

Recently, I only use Barracuda for machine learning like [these projects](https://github.com/search?q=barracuda+user%3Akeijiro).

I'd recommend not using hard-coded approaches like Ngx. Barracuda is more convenient, general purpose and continuously maintained.

**Comment by ethanstickley** [comment]
Thank you for the quick response!
